from openai import OpenAI
import json
import tqdm

client = OpenAI()

system_prompt = " ".join((
    "You are an expert latex interpreter. I will provide you two answers.", 
    "The expected answer and the answer that was generated by the model.", 
    "Your task is to tell whether both the answers are mathematically equivalent or not.",
    "Give your answer in a single word `yes` or `no`.",
    "Give your reasoning after Reasoning: tag, and the final verdict after Verdict: tag.",
))

def llm_judge(actual_answer, model_answer):

    prompt = "\n".join((
        f"expected_answer: {actual_answer}",
        f"model_answer: {model_answer}"
    ))

    completion = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    result = completion.choices[0].message.content
    result = result.rsplit("Verdict:", maxsplit=1)[-1].strip()

    return result == "yes", completion.choices[0].message.content

file_to_check = "results/qwen2.5_0.5b_1shot_GSM8K.json"
with open(file_to_check, "r") as f:
    results_dict = json.load(f)

score = 0
for datapoint in tqdm.tqdm(results_dict):
    if datapoint["actual_answer"] == datapoint["model_answer"]:
        score += 1
    elif llm_judge(datapoint["actual_answer"], datapoint["model_answer"])[0]:
        score += 1
    elif llm_judge(datapoint["actual_answer"], datapoint["model_entire_answer"])[0]:
        score += 1
    
print(score/len(results_dict))

